### PR TITLE
Update index.html for Pagination

### PR DESCRIPTION
**Pull request by Rychillie**
#231 It's solved!

### CODE REVIEW

**Comment by jehartzog** [comment]
It looks like your changes to `disquis.html` were just indentation, and from `blog/index.html` you removed the `{% if post.category == 'blog' %}` conditional.

If you look at an [example project](https://github.com/sergiokopplin/indigo/blob/gh-pages/_posts/2016-01-23-indigo-jekyll-theme.markdown) and an [example blog post](https://github.com/sergiokopplin/indigo/blob/gh-pages/_posts/2015-02-24-markdown-extra-components.markdown) you'll notice they both have a tag in the header of `category` with the type `blog` or `project`.

If you remove that conditional describe above, then projects would show up in the blog timeline, which is a design decision you may which to change for your blog, but the current method works sense for most cases.

**Comment by Rychillie** [comment]
After months of testing the only problem I had in pagination is that when you have the "Blog" category to read it does not show anything, removing it works perfectly!

The disquis.html I'm doing some tests

**Comment by sergiokopplin** [comment]
Hey @Rychillie, have you tested?

**Comment by Rychillie** [comment]
@sergiokopplin I'm testing on rychillie.net making several interesting modifications to go on the air.

**Comment by jehartzog** [comment]
This seems to fix something only experienced by one user and breaks some desired functions, closing this out.

**Pull request closed without merging**
