### PR TITLE
Adding translation from English to Russian

### PR DESCRIPTION
**Pull request by denisorehovsky**
I'm trying to add a translation for the theme. But I have some problems with that:

1. I don't know how to translate dates.
2. I don't know how to properly declare a variable in the Front Matter. What I am trying to do is not working:

---
layout: page
title: {{ site.data.ui-text[site.locale].home_label }}
---

instead of 

---
layout: page
title: Home
---

### CODE REVIEW

**Comment by sergiokopplin** [comment]
Hey @apirobot, sorry for the delay.
Are you using this on your own application? Is the first time that someone ask about a translation. I also don't like in un/uk and i speak portuguese.

I'm not sure if we need this, we can add some documentation about 'how to translate' the theme. I think it will get complex if we add more than 3 languages, for example. (Russian, English, Italian, Portuguese, etc)

**Comment by denisorehovsky** [comment]
I have tried to translate it, but I didn't succeed. My problems I described above. I think you're right about the complexity of it. It's not worth it.

I've just thought that it would be awesome if such a good theme had the translation. And it would be more awesome if you could change the language just by changing one line of the code :)

**Comment by sergiokopplin** [comment]
We can simplify that to be easy when someone must translate.
Which kind of problem you had?

**Comment by sergiokopplin** [comment]
Closing for now due to inactivity.

**Pull request closed without merging**
