### PR TITLE
fix: exclude file from being generated on build (#2)

### LINKED ISSUE #327: Travis.sh is generated inside _site
Is it possible to exclude some files when building _site ?

Steps to reproduce : 

- `bundle exec jekyll serve --config _config.yml,_config-dev.yml`
- Go to `http://localhost:4000/travis.sh`

Output : 
File is downloaded.

Expected : 404, because this file shouldn't be generated in `_site`

### PR DESCRIPTION
**Pull request by sylvainmetayer**
Fix #327

### CODE REVIEW

**Comment by mehmandarov** [comment]
Looks good to me. 👍

**Comment by sylvainmetayer** [comment]
I've also added `FAQ.md` that doesn't need to be included.

**Review by mehmandarov — APPROVED** [review]
Looks good to me. What do you say, @sergiokopplin?

**Comment by sergiokopplin** [comment]
nice!

**Pull request merged**
