### PR TITLE
Update Google Analytics code

### PR DESCRIPTION
**Pull request by wchliao**
According to Google Analytics library, [ga.js](https://developers.google.com/analytics/devguides/collection/gajs/) is a legacy library.
Therefore, I update the code, according to [here](https://support.google.com/analytics/answer/1008080).

### CODE REVIEW

**Review by jehartzog — APPROVED** [review]
This one was a little unclear, as I recently made a website and definitely used the [Universal Analytics](https://support.google.com/analytics/answer/2790010?hl=en) method, which runs off `analytics.js`.

On Google's legacy `ga.js` upgrade page, they still list the [`analytics.js`](https://developers.google.com/analytics/devguides/collection/upgrade/reference/gajs-analyticsjs) option first.

Going from `analytics.js` to `gtag.js` is a [non-trivial](https://developers.google.com/analytics/devguides/collection/gtagjs/migration), so it's probably not worth for any sites that have spent time carefully integrating Google Analytics.

Luckily I don't think that really applies here, and the current recommend solution using `gtag.js` is the future-proof best choice.

**Review by mehmandarov — APPROVED** [review]
lgtm! 👍

**Comment by mehmandarov** [comment]
What do you say, @sergiokopplin?

**Comment by mehmandarov** [comment]
This one is ready to be merged. Just waiting on your review, @sergiokopplin. :-)

**Comment by sergiokopplin** [comment]
any additions on that @jehartzog?

**Review by sergiokopplin — APPROVED** [review]

**Comment by jehartzog** [comment]
No additions, looks like things have changed since my last comment. LGTM

**Pull request merged**
