### PR TITLE
Made initpost.sh executable

### PR DESCRIPTION
**Pull request by mehmandarov**

### CODE REVIEW

**Comment by sergiokopplin** [comment]
Can you explain the pr?

Thanks!

**Comment by mehmandarov** [comment]
The bash file was cloned without executable bit (rw-r--r--, or mode 644) on *nix systems and Mac OSX. I have changed that so it is now executable (rwx-r-x-r-x, or mode 755). Now you can run it like this:

``` bash
$> ./initpost.sh -c Some fancy title
```

**Comment by sergiokopplin** [comment]
Oh, nice! Thank!

**Comment by mehmandarov** [comment]
You are welcome! :-)

**Pull request merged**
