### PR TITLE
fix: alt element defined twice inside author block

### LINKED ISSUE #330: Alt element defined twice
https://github.com/sergiokopplin/indigo/blob/5f2608ffc8bac9f30222c141e0299e13faed1f9d/_includes/author.html#L3

There is two alt elements, which cause html-proofer to fail. (`ERROR: Attribute alt redefined`)

I don't know which one to remove, but I believe the `author selfie` is kind of useless if there is already the author name ?

### PR DESCRIPTION
**Pull request by sylvainmetayer**
This fix #330

### CODE REVIEW

**Review by mehmandarov — APPROVED** [review]
lgtm!

**Comment by mehmandarov** [comment]
Thank you for your pull request, @sylvainmetayer! 👍

**Comment by mehmandarov** [comment]
Ping, @jehartzog 👋 😃

**Comment by sergiokopplin** [comment]
hey @mehmandarov, really thanks for the help!!!!!

**Comment by mehmandarov** [comment]
No worries, @sergiokopplin. Thought it would be nice to close a few issues. 👍

**Comment by sergiokopplin** [comment]
I have commented on every single issue and pr, let's keep it going. thanks again @mehmandarov

**Pull request merged**
