### PR TITLE
Adding pagination in blog posts list

### PR DESCRIPTION
**Pull request by siddhantjain**
Hey,

I have added the pagination to the blog posts. Can you have a look?

I was not sure what sort of design to use for the next and previous page options, so i went ahead with the most basic thing. We can probably change that as well.

### CODE REVIEW

**Comment by sergiokopplin** [comment]
I have to do some css,  even so nice work!

**Comment by sergiokopplin** [comment]
merged!
i fixed some whitespaces, some tabs and i added the pagination as option
thank you for your pull request
you are a contributor now

**Comment by siddhantjain** [comment]
Hey,

Thanks for adding me as a contributor!

Could you please let me know when you push the css changes. I wanted to
pick up CSS myself and the changes you might make will help me with
understanding it better.

thanks.

Best,
Siddhant

**Comment by sergiokopplin** [comment]
Its all there! You can take a look inside the stylus
folder,_pagination.styl file

**Pull request merged**
