### PR TITLE
Fixing several reported bugs

### PR DESCRIPTION
**Pull request by mehmandarov**
* Fixed `does not have a valid date in the YAML front matter` error while building the site. More info: https://github.com/sergiokopplin/indigo/issues/348.
* Added info on how to run this site in a Docker container in FAQ.
* Fixed og:image for posts. More info: https://github.com/sergiokopplin/indigo/issues/350.

### CODE REVIEW

**Comment by sylvainmetayer** [comment]
Couldn't we go further and provide a docker-compose ready to use ? People who want to use docker would just have to run `docker-compose up -d` and they will be ready to go. People who don't will just ignore the file.

**Comment by mehmandarov** [comment]
@sylvainmetayer: Sure, we could do that! I just linked to what I have for now. That will come in the next round I guess. :-)

**Comment by sylvainmetayer** [comment]
I already have a docker-compose setup for my fork, I can provide a PR if needed.

**Comment by mehmandarov** [comment]
Sure, why not, @sylvainmetayer! :)

**Comment by sylvainmetayer** [comment]
I've submitted #352 :)

**Pull request merged**
