### PR TITLE
Refactor social-links.html to use information encoded in _data/social-links.yml

### PR DESCRIPTION
**Pull request by vivekkrish**
This PR refactors the social links element of the page, by using data encoded in the `_data/social-links.yml` file to construct the link outs.

This PR also adds the following:
+ Add placeholder links to several scientific sites (like Google Scholar, PubMed, etc.)
+ Add supporting SVG icons for scientific sites

Documentation: https://vivekkrish.com/indigo/adding-configuring-social-links/

### CODE REVIEW

**Comment by vivekkrish** [comment]
Updated PR now allows user to specify ordering of the social links via an array in `_config.yml`

**Comment by sergiokopplin** [comment]
Good one! Nice catch!

Have you testes properly? The code LGTM, so we can merge that.
What you guys think @jehartzog @mehmandarov?

**Comment by vivekkrish** [comment]
Thanks, @sergiokopplin. (BTW, thank you so much for this theme!)

I have done some minimal testing w.r.t enabling/disabling specific links in the `_config.yml` File and then looking to see whether the appropriate icon/link is rendered on the page. This code is currently active on my site https://vivekkrish.com (please refer to the [`_config.yml`](https://github.com/vivekkrish/vivekkrish.github.io/blob/master/_config.yml#L43-L74) snippet).

If you think there might be any caveats to this approach, I'm happy to review it further and fix things.

**Comment by mehmandarov** [comment]
I have not been able to teste the code now, but it looks fine, @sergiokopplin. :-)

**Comment by sergiokopplin** [comment]
@vivekkrish nice work!

can we do the same without a plugin (_plugins/concat.rb)?
For some people is too difficult to understand and update things. We have a lot of non-developers here.

Is that possible? What you think @vivekkrish ?

**Comment by vivekkrish** [comment]
Hi @sergiokopplin, thank you!

I took a look at the current GitHub pages dependency versions (https://pages.github.com/versions/) and saw that it now uses liquid~4.0.0. This particular version of liquid has support for the `concat()` method.

As such, I have removed the plugin code that I added.

**Comment by jehartzog** [comment]
This looks great!

**Comment by vivekkrish** [comment]
Hi @sergiokopplin, can these changes be merged?

Since your last comment, I have added a blog post which describes this new functionality, that should appear at the link https://koppl.in/indigo/adding-configuring-social-links, once the code changes are merged.

Thank you!

**Comment by vivekkrish** [comment]
Hi @sergiokopplin (and other maintainers, @jehartzog and @mehmandarov) -
Can this PR be merged? Or should this wait until #262 is resolved?

Thank you!

**Comment by jehartzog** [comment]
Hey thanks for being patient, this was enough awesome work that it actually took a little time to read through everything and test it out. You obviously have some good experience contributing and writing docs.

These changes are fully backward compatible, streamline the code a good deal, and add new optional functionality along with documentation on how to use it. @sergiokopplin I definitely recommend merging this in as is, it looks great.

The only questions I had I was able to figure out through testing, and I wrote a tiny bit of [documentation](https://github.com/jehartzog/indigo/commit/fadbbfca00ea0e846553a4995656e29f40dfc3f6) just to make this clear to anyone else. You can copy that, or re-write how you think is best, since you obviously know how to write good documentation. Or you can decide not to include it, either way I recommend this PR be merged.

**Comment by vivekkrish** [comment]
Hi @jehartzog - Thanks so much for your review and overwhelmingly positive comments! I really appreciate you taking the time out to do this.

Thanks also for adding a new section to the documentation about backwards "Compatibility". Your suggested additions look good! I will copy your text and make another commit to this PR, and then it should be good to go.

**Comment by vivekkrish** [comment]
Hi @sergiokopplin - Are there any plans to merge this PR? Look forward to your thoughts.
Thank you!

CC @mehmandarov @jehartzog 

Documentation: https://vivekkrish.com/indigo/adding-configuring-social-links/

**Comment by mehmandarov** [comment]
@vivekkrish Thanks for the PR. I am trying to merge it, but since it contains links to the pages that don't (yet) exist in the post it beaks the build and stops me from merging. Could you split it in two PRs – one with the code and one with the blogpost. You should be able to see for yourself if your commit/PR passes all the tests.

**Comment by sergiokopplin** [comment]
@mehmandarov agree!!!!!

**Comment by vivekkrish** [comment]
Thanks for looking into this PR! I will merge upstream changes from `gh-pages` branch, clean things up and fix this PR later today.

**Comment by vivekkrish** [comment]
OK, PR should be good to go. I will create a new PR with the blog post once this is merged.

**Comment by sergiokopplin** [comment]
nice @vivekkrish, the code seems ok, i'll test it out later, thanks again

**Comment by cfgnunes** [comment]
Great code @vivekkrish!

**Comment by sergiokopplin** [comment]
Hey @vivekkrish @mehmandarov @cfgnunes we should this it again before merge. I've accepted several others merge requests, so I'm not sure if this is still working. Can you help us @vivekkrish ? And sorry for the delay of almost 2 years 🙍🏻‍♂️

**Comment by sylvainmetayer** [comment]
Hey @vivekkrish  !

Sorry your PR got closed without notice :confused: 

We now use Github actions to deploy site to github pages, which allow use to use custom gems.

Could you provide your PR against master please ? 

cc @sergiokopplin

**Comment by sergiokopplin** [comment]
Agree!! We should open it again

**Pull request closed without merging**
