### PR TITLE
Fix social links

### PR DESCRIPTION
**Pull request by npvinhphat**
[Sorry for any wrong information since first pull request ever]

Hi, I encounter a bug with the social links file (_includes/social-links.html).

I just add a simple fix:

Change: 
`{% if site.facebook != false %}`

To:
`{% if site.facebook %}`

Then I can remove any unnecessary social links.

### CODE REVIEW

**Comment by sergiokopplin** [comment]
Thank you for your pull request.
I can't merge because it has your commits for other files.

You have to delete them from the pull request first.

**Comment by sergiokopplin** [comment]
@npvinhphat i'll fix that without your pull request.
I put your name in the contributors ok?

Thank you again!

**Comment by npvinhphat** [comment]
Hi, it would be great if you can help me fix it :D. Sorry I don't know how to change the commits in a pull request.

I'll close this for now :)

**Comment by sergiokopplin** [comment]
[done!](https://github.com/sergiokopplin/indigo/commit/41d4e2a013a9a427a80a994f9b80f6c9fbefbf3d)

**Comment by npvinhphat** [comment]
Thanks!

**Pull request closed without merging**
