### PR TITLE
Added Yandex.metrica support.

### PR DESCRIPTION
**Pull request by 3manuek**
Added yandex-metrica support for analytics

### CODE REVIEW

**Comment by sergiokopplin** [comment]
Have you tested that? Do it works properly? The code looks good to me! :)

**Comment by mehmandarov** [comment]
Great job, @3manuek! Couple of thoughts here:
1. It seems like the image added is missing the alt-text here, breaking the HTML-proofer. Can you please fix that?
2. I would suggest using existing file and property naming notation. For the file, it would be something like `analytics-yandex-metrica.html`, and for the property name in `_config.yml` it would be something like `analytics-yandex-metrica`.

What do you guys think?

**Comment by 3manuek** [comment]
Hi @sergiokopplin ! Sorry, just saw the comment. It is working at my end (using it in my personal site).

**Comment by 3manuek** [comment]
@sergiokopplin @mehmandarov Hmm that's weird, let me check what could be wrong. Thanks for all the input! Regarding the naming notation, I'm open to any changes.

I didn't saw the message 'cause I forgot to _watch_ the project.

**Comment by sergiokopplin** [comment]
Closing for now due to inactivity.

**Pull request closed without merging**
