### PR TITLE
Allow css caching and fix orphaned assets/styles/main.css

### PR DESCRIPTION
**Pull request by tombusby**
I was making a couple of alterations to main.css and had some serious confusion as to why it wasn't working properly when I did a `jekyll build`. I was being copied to `_site` properly etc.

After tracing through I noticed that `assets/styles/main.css` was orphaned, it gets included from `_includes` which means the same CSS has to be loaded for every page.

All this seems a little confusing and inefficient, so I've removed `_includes/main.css` and pointed the site at `/assets/styles/main.css`.

### CODE REVIEW

**Comment by tombusby** [comment]
Ignore this for now, I'll modify it if/when you approve my other PR.

Apologies, I was a little sloppy about reading the README. Was playing with a personal-blog site based on the 0.3.0 release and copying my fixes over to the fork. Will be more careful in future.

**Comment by sergiokopplin** [comment]
Ok, no problems.

Can we close for now?

**Comment by tombusby** [comment]
Just about to push a new commit.

**Comment by sergiokopplin** [comment]
I'm not going to accept that pull request because it changes the way the build works.

The css is injected in the page, inline and minified. That's why it's so fast to load the page.
The CSS from the includes is necessary because the file is included after by this location.

**Comment by tombusby** [comment]
I'm aware of that. If you look at the commit you'll see I removed that include so that the css could be loaded from cache, rather than included in-full on every page.

Currently the main.css that ends up in `_site/assets/styles/main.css` is totally orphaned.

**Comment by tombusby** [comment]
So what I'm saying is: we should remove either the `_site/assets/styles/main.css` and just use the one in `_includes` or (as this PR did) load it in from `_site/assets/styles/main.css` and remove the one in `_includes`.

Is it definitely faster to have the CSS in-line on every page than to allow the browser to cache it as a separate file?

**Comment by sergiokopplin** [comment]
We can change this, of course.
Take a look here: https://developers.google.com/speed/docs/insights/OptimizeCSSDelivery

What you think?

**Comment by tombusby** [comment]
I guess we should actually run tests to see which is better. I'll have a look tomorrow if I get a chance.

I'm waiting for a client to get back to commit to a new project, so I have a bit of spare time over the next few days.

**Pull request closed without merging**
