### PR TITLE
Refactor social-links.html to use information encoded in _data/social-links.yml

### PR DESCRIPTION
**Pull request by vivekkrish**
This is a follow up to PR #251, which was the initial implementation, but never got a chance to be merged.

This PR refactors the social links element of the page by using data encoded in the `_data/social-links.yml` file to construct the link outs.

This PR also adds the following:
+ Add placeholder links to several scientific sites (like Google Scholar, PubMed, etc.)
+ Add supporting SVG icons for scientific sites

Documentation: https://vivekkrish.com/indigo/adding-configuring-social-links/

### CODE REVIEW

**Comment by vivekkrish** [comment]
Hi Maintainers -

I've revived my previously closed PR by synchronizing my fork with the latest changes, resolving any conflicts and re-issuing this PR. But I'm noticing that the CI tests are running. Is there anything else I should be doing to get this PR going?

Please let me know.

Thanks!

**Comment by vivekkrish** [comment]
Nevermind, just realized that the tests have run (and failed due to some HTMLProofer errors). I will resolve them now!

**Comment by vivekkrish** [comment]
Looks like the tests are a success: https://travis-ci.org/github/sergiokopplin/indigo/builds/702820098. But for some reason, it doesn't reflect on the UI here. Please could someone check?

Thanks!

**Review by IamLizu — COMMENTED** [review]
does this article exists?

**Comment by vivekkrish** [comment]
> does this article exists?

Yes, it does: https://github.com/sergiokopplin/indigo/pull/453/files#diff-02f1d2b5b2bce810ea310595d2d348ee, included in this PR.

**Comment by sergiokopplin** [comment]
I think this is too old now. We should close it and open it again if we think it's necessary. Thanks for your contributions @vivekkrish

**Pull request closed without merging**
