### PR TITLE
Fix hidden posts appearing in blog navigation

### PR DESCRIPTION
**Pull request by tpict**

### CODE REVIEW

**Comment by mehmandarov** [comment]
Looks good to me. What do you guys think, @jehartzog and @sergiokopplin?

**Review by mehmandarov — COMMENTED** [review]
👍

**Review by mehmandarov — APPROVED** [review]
Looks good to me. What do you guys think, @jehartzog and @sergiokopplin?

**Review by jehartzog — APPROVED** [review]
This one is more complicated, we are kind of masking the symptom here rather than really fixing the bug that was exposed.

I'm good with merging this, but I opened up #292 to track with a possible better fix later.

**Comment by sergiokopplin** [comment]
do you guys thinks is it safe to merge? @mehmandarov @jehartzog

**Comment by jehartzog** [comment]
LGTM

**Comment by mehmandarov** [comment]
LGTM! Merging. 👍

**Comment by sergiokopplin** [comment]
nice!

**Pull request merged**
