### PR TITLE
Added title image to posts

### PR DESCRIPTION
**Pull request by jehartzog**
Currently the 'img' tag for posts does not do anything I could identify. For my site I wanted to be able to optionally add a small image to the title.

For this PR, I used the Jeykll logo as an example, screenshots are below.

screenshot 2016-05-04 20 21 07

View on a small screen (responsive)
screenshot 2016-05-04 20 21 37

### CODE REVIEW

**Comment by sergiokopplin** [comment]
Hey @jehartzog, thank you for the pull request. I'll take a look later.

**Comment by jehartzog** [comment]
No worries, this is really just a style point so you may not even want it. I'm adding items for my own page and will be happy to share any of the work I've done it there is a desire to tailor it for the template here. I'm still putting everything together, but you can see how I've built on the template [here](http://www.johnehartzog.com) (or the source on [GitHub](https://github.com/jehartzog/jehartzog.github.io)).

**Comment by sergiokopplin** [comment]
I'm looking this right now. (your blog is looking nice man! :metal:)

**Comment by sergiokopplin** [comment]
@jehartzog. Thank you for your pull request.

---

I don't like the way the images are beside the title. Seems weird for me, mainly in medium screens.
What you think about puting the images above the title in the center?

**Comment by jehartzog** [comment]
Having the images in the center seems good too, I'm not a strong designer so I don't really focus on it. I just didn't understand why the `img` tag was there before seemingly unused and wanted to use it.

I might play around with it and try to clean it up to make it fit the theme better.

**Comment by jehartzog** [comment]
It does look better, I shifted my own page to use it. Thanks!

screenshot 2016-05-17 19 30 30

**Comment by sergiokopplin** [comment]
Your pull request has some conflicts and i can't merge the commit. Can you solve them and push the files?

**Comment by jehartzog** [comment]
Fixed, sorry it was conflicting with the merges from my other PR's, I'm still pretty new to GitHub!

**Pull request merged**
