### PR TITLE
Show next and prev links in blog post

### PR DESCRIPTION
**Pull request by jehartzog**
screenshot 2016-05-30 18 26 19

### CODE REVIEW

**Comment by sergiokopplin** [comment]
Nice idea! I'll test this later, but i think it's already done! Thank you! Again!

**Comment by sergiokopplin** [comment]
I'm thinking, we have the related posts inside the post, why we need another thing to create the relation between them?
I don't know if this is necessary. What you think?

---

@jehartzog thank you for the pull request. 👍

**Comment by jehartzog** [comment]
My theme is a less "minimal" than what you originally created, so I would agree this probably doesn't need to be added by default. If you are unsure, you can add the code and then leave it disabled by default on all pages (it is configurable in _config.yml) and people can turn it on if they want.

No worries if you don't think it fits though, it was super quick to create the PR.

**Comment by sergiokopplin** [comment]
@jehartzog you are right! Merging. Thank you again!

**Pull request merged**
