### PR TITLE
Add font awesome icons

### PR DESCRIPTION
**Pull request by sylvainmetayer**
Only used icons are generated.

add [jekyll-fontawesome-svg gem](https://github.com/sylvainmetayer/jekyll-fontawesome-svg)

Their is maybe some CSS improvements to make, as I'm not really good with that.

### CODE REVIEW

**Comment by sergiokopplin** [comment]
hey @sylvainmetayer @mehmandarov @jehartzog, there's a lot of people opening pull request adding new icons.
we need to merge this, do you guys agree? any SEO concerns? I think we might increase the js/icons payload, but im not sure.

There's another gem https://github.com/drewish/jekyll-font-awesome-sass.
Why this option is better than this another one @sylvainmetayer?

**Comment by sylvainmetayer** [comment]
This PR won't add any more js/icons. It will add a few css line, but I think that it negligible. 

The main difference between this option (that I developed because I couldn't find any alternative, or haven't found one that fit my needs) and https://github.com/drewish/jekyll-font-awesome-sass is that jekyll-font-awesome-sass will load all assets and javascript, even if you use only one icon (from what I've seen, correct me if I'm wrong). 

It also require javascript which I think could be avoided to display icons (I will consent to use javascript to animate icons, but display icon should not require javascript)

This option will use no javascript, and will load only the used icon on each page. It will generate SVG icon from the official Font Awesome one's, allowing to choose among thousand of icons, but only include the used one.

From a SEO concern, I see no difference between the 2 solutions.

**Comment by sergiokopplin** [comment]
Hey @sylvainmetayer, i've checkout your branch here and it's working nice. The styles are a little bit different form the original icons.

As we update this styles to the original ones, i see no problem merging this! It looks awesome and fixes a lot of related issues.

YOURS:
image

ORIGINAL:
image

**Comment by sylvainmetayer** [comment]
Hey @sergiokopplin is this better like this ? 

file

**Comment by sylvainmetayer** [comment]
Hello @sergiokopplin, did you get time to review this one ?

**Comment by cbrueffer** [comment]
I like this PR @sylvainmetayer, thanks! The changes seem to throw centering off a bit though, see e.g. uneven start/end spacing when comparing John Doe, icons, and navigation bar, and comparing the two lines in the footer. Particularly when comparing to Sergio's Original screenshot.

**Comment by sylvainmetayer** [comment]
@cbrueffer Thanks for the feedback ! I'll try to update next week the code to better match the original icons but I'm not quite good with CSS. If you can, could you provide me details on what to edit/how to please ?

**Comment by cbrueffer** [comment]
I'll give it a shot. Do you think your gem approach is easily transferable to Academicons (https://jpswalsh.github.io/academicons/)? This would make integration with https://github.com/sergiokopplin/indigo/pull/251 easier.

**Comment by sylvainmetayer** [comment]
I'll look into it next week. For what I've seen their is no single svg icons, only a big svg containing all icons. Maybe I can parse it to extract icons into single file and use the same gem approach to load only used icons.

**Comment by cbrueffer** [comment]
The centering problems come from the new icons having extra whitespace in addition to the icon itself, e.g. about 50% of the included icon width is white (or rather, alpha, I suppose). I don't know whether this comes from the way the fontawesome gem is build, or has a different reason.

The following patch fixes the centering issues by compensating for the extra whitespace: https://github.com/cbrueffer/indigo/commit/ae9e47085ac1147924849a9cd4c547498174123f

**Comment by sylvainmetayer** [comment]
Hello @cbrueffer 

Sorry about the delay. I've added your change to this branch. It should be OK now.

I did not get time to look into academic icons. But I've seen the svg, and with some parsing of the file, I should be able to do it without too much trouble. I'll let you know when I'm done so you can test it !

@sergiokopplin Do you think we could merge this one now ? 

It seems that the CI did not pass because of broken links. Is it possible to trigger it again ? I've manually check, links are available.

**Comment by sylvainmetayer** [comment]
@cbrueffer I've released a 0.2.0 version of my gem which include academicons. 

See https://github.com/sylvainmetayer/jekyll-fontawesome-svg/commit/73e17b9d9bde1d9eef94bf37a2cca60b948c39ae

Could you test it and tell me if it work as you expected please?

**Comment by sylvainmetayer** [comment]
@cbrueffer I've released it as a separated gem as name were inconsistent, see https://github.com/sylvainmetayer/jekyll-academicons-svg/ if you want to test it.

However, style is far from being perfect

**Comment by cbrueffer** [comment]
Thanks @sylvainmetayer , I hope to test it this weekend.

**Comment by sylvainmetayer** [comment]
@sergiokopplin did you get any time to review this PR ? It would be great to merge it so others would benefit it.

**Comment by sergiokopplin** [comment]
I've made some changes, now it's ready! It was a few bugs

**Pull request merged**
