### PR TITLE
Icons changed to FontAwesome from SVG.

### PR DESCRIPTION
**Pull request by anirudhbiyani-zz**
Creating this PR as per Issue #259. 

This might need some code refactoring and some changes in the CSS, not sure about it thought, would be great if someone can review it.

Also, the SVG icon data is still present in the repo, if can be removed if all the changes in this PR are good to go.

### CODE REVIEW

**Comment by sergiokopplin** [comment]
Awesome work @anirudhbiyani! Really nice!

---

Doubt: any way to have less files? It seems a lot and it increase a lot the project files. Can we find a "different but same" solution? But awesome work, again!

**Comment by anirudhbiyani-zz** [comment]
@sergiokopplin yeah! I understand that. One thing that can be done is use the gem file for FA rather than referencing the files itself. I did try using the gem but it was breaking the project for me. 

Maybe if it is possible for you or any of the contributors to try that and do let me know if any help is required. The gem has already been included in Gemfile, the style.scss would have to be edited to reflect the same.

**Comment by vivekkrish** [comment]
Hi All,

This is definitely a great idea! However, it doesn't address a situation where users might want to utilize icons that are not part of the **Font Awesome** (FA) manifest.

Specifically, some of the scientific/academic websites like Google Scholar, ResearchGate, etc. do not have FA icons available. Similar to FA, there is a collection of icons called [Academicons](http://jpswalsh.github.io/academicons/) which could be used (but does not have a relevant `gem`).

An alternative implementation would be to rely on Content Delivery Networks (CDNs) such as Cloudflare, Google, etc. that host and make these assets available to websites all over the world. For example, here are the available CDNs:
* Font-Awesome: https://cdnjs.com/libraries/font-awesome
* Academicons: https://cdnjs.com/libraries/academicons

In order to implement this, asset URLs would need to be placed within the `<head>` element of the HTML (in `_layouts/default.html`).
```
<head>

<link rel="stylesheet" type="text/css" 
         href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

{% if site.academicons %}
<link rel="stylesheet" type="text/css" 
         href="//cdnjs.cloudflare.com/ajax/libs/academicons/1.8.1/css/academicons.min.css">
{% endif %}

</head>
```

This does introduce an external dependency, but these CDNs generally tend to have high availability.

Thoughts?

**Comment by jehartzog** [comment]
Sorry for jumping on this late, but I have some thoughts about the work being doing with this PR.

The overall idea behind this theme is that 1) it's minimalist and 2) it's _fast_.

Not just your average optimized website, but actually crazy fast. It serves practically everything needed inline in a small initial response to a browser to allow a crazy quick render. The only things that need a round trip to fetch are the images which we currently don't bother doing any base64 encoding to include.

While the use of the inline SVG's is slightly more cumbersome than just linking to a CDN version of FA, I'd personally prefer this approach as the focus of this theme is to make a super-fast and super-simple personal page.

Including all of the FA files in the project and linking to them locally has the same issue as with the CDN, and I don't think that's the right approach either.

Of course I'm very happy to see this PR being worked on and never want to discourage someone from contributing, but I don't recommend this be merged, as is, into the main theme.

**Comment by sylvainmetayer** [comment]
Hello, 

I've been facing the same issue as you, and I've made a Jekyll Gem that include only the used icons so performance are not affected. 

I've just released it, if you are interested you can find it [here](https://github.com/sylvainmetayer/jekyll-fontawesome-svg)

I'm also using it in my [Jekyll blog](https://github.com/sylvainmetayer/sylvainmetayer), based on this theme. There is some work to do, especially to deal with some CSS issue but it is usable. 

~~If you are interested, I can submit a PR including this gem and converting all svg.~~

Edit : I've submitted PR #338 if you want to review it.

**Pull request closed without merging**
