### PR TITLE
Author's tweeter is now author specific

### PR DESCRIPTION
**Pull request by NicolasHug**
Hi,
And thanks for this great theme!

I changed the  twitter account used in the `author` section of a post to the actual [post author's tweeter](https://github.com/sergiokopplin/indigo/blob/gh-pages/_config.yml#L61). It is  currently the global site's twitter. 

Nicolas

### CODE REVIEW

**Comment by sergiokopplin** [comment]
Nice! Have you seen other places with the same problem? Can you fix these other places?

**Comment by NicolasHug** [comment]
Hi,
No `site.twitter` is only used in `social-links.html`, which is correct.

Nicolas

**Comment by mehmandarov** [comment]
This sounds like a reasonable change. 👍 

Slightly offtopic: I have also troubles with twitter info generated by the jekyll-seo plugin. How is it working for you, @NicolasHug?

**Comment by mehmandarov** [comment]
Tested. It works fine! 👍

**Comment by sergiokopplin** [comment]
Thanks @mehmandarov

**Pull request merged**
